[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = "3.0.0-rc.8"
serde = { version = "1.0.132", features = ["derive"] }
snap = "1.0.5"

[build-dependencies]
rand = "0.8.4"
temp-dir = "0.1.11"

[dev-dependencies]
rand = "0.8.4"
temp-dir = "0.1.11"
